routes/backend.php
        Route::patch('orders/{orders}', ['as'=> 'orders.update', 'uses' => 'Backend\OrderController@update']);
        Route::get('orders/{id}/delete', array('as' => 'orders.delete', 'uses' => 'Backend\OrderController@getDelete'));
        Route::get('orders/{id}/destroy', array('as' => 'orders.total-destroy', 'uses' => 'Backend\OrderController@destroy'));
        Route::get('orders/{id}/confirm-delete', array('as' => 'orders.confirm-delete', 'uses' => 'Backend\OrderController@getModalDelete'));
        Route::get('orders/{id}/confirm-destroy', array('as' => 'orders.confirm-destroy', 'uses' => 'Backend\OrderController@getModalDestroy'));
        Route::get('orders/{id}/restore', array('as' => 'restore/order', 'uses' => 'Backend\OrderController@getRestore'));
        Route::get('orders/{orders}', ['as'=> 'orders.show', 'uses' => 'Backend\OrderController@show']);
        Route::get('orders/{orders}/edit', ['as'=> 'orders.edit', 'uses' => 'Backend\OrderController@edit']);
        Route::get('deleted_orders',array('as' => 'deleted_orders','before' => 'Sentinel', 'uses' => 'Backend\OrderController@getDeletedOrders'));

        # Personal Shopper Management
        Route::get('personalShoppers', ['as'=> 'personalShoppers.index', 'uses' => 'Backend\PersonalShopperController@index']);
        Route::get('personalShoppers/data',['as' => 'personalShoppers.data', 'uses' =>'Backend\PersonalShopperController@data']);
        Route::post('personalShoppers', ['as'=> 'personalShoppers.store', 'uses' => 'Backend\PersonalShopperController@store']);
        Route::get('personalShoppers/create', ['as'=> 'personalShoppers.create', 'uses' => 'Backend\PersonalShopperController@create']);
        Route::put('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.update', 'uses' => 'Backend\PersonalShopperController@update']);
        Route::patch('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.update', 'uses' => 'Backend\PersonalShopperController@update']);
        Route::get('personalShoppers/{id}/delete', array('as' => 'personalShoppers.delete', 'uses' => 'Backend\PersonalShopperController@getDelete'));
        Route::get('personalShoppers/{id}/destroy', array('as' => 'personalShoppers.total-destroy', 'uses' => 'Backend\PersonalShopperController@destroy'));
        Route::get('personalShoppers/{id}/confirm-delete', array('as' => 'personalShoppers.confirm-delete', 'uses' => 'Backend\PersonalShopperController@getModalDelete'));
        Route::get('personalShoppers/{id}/confirm-destroy', array('as' => 'personalShoppers.confirm-destroy', 'uses' => 'Backend\PersonalShopperController@getModalDestroy'));
        Route::get('personalShoppers/{id}/restore', array('as' => 'restore/personalShopper', 'uses' => 'Backend\PersonalShopperController@getRestore'));
        Route::get('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.show', 'uses' => 'Backend\PersonalShopperController@show']);
        Route::get('personalShoppers/{personalShoppers}/edit', ['as'=> 'personalShoppers.edit', 'uses' => 'Backend\PersonalShopperController@edit']);
        Route::get('deleted_personalShoppers',array('as' => 'deleted_personalShoppers','before' => 'Sentinel', 'uses' => 'Backend\PersonalShopperController@getDeletedOrders'));

        # Service Request
        Route::get('serviceRequests/packages', ['as'=> 'serviceRequests.packages.index', 'uses' => 'Backend\ServiceRequestController@index']);
        Route::get('serviceRequests/packages/data',['as' => 'serviceRequests.packages.data', 'uses' =>'Backend\ServiceRequestController@requestServicePackagesData']);
        Route::get('serviceRequests/orders', ['as'=> 'serviceRequests.orders.index', 'uses' => 'Backend\ServiceRequestController@index']);
        Route::get('serviceRequests/orders/data',['as' => 'serviceRequests.orders.data', 'uses' =>'Backend\ServiceRequestController@requestServiceOrdersData']);
        Route::get('serviceRequests/packages/{package}/edit',['as' => 'serviceRequests.packages.edit', 'uses' =>'Backend\ServiceRequestController@requestServicePackagesEdit']);
        Route::get('serviceRequests/orders/{order}/edit',['as' => 'serviceRequests.orders.edit', 'uses' =>'Backend\ServiceRequestController@requestServiceOrdersEdit']);
        Route::post('serviceRequests/update',['as' => 'serviceRequests.update', 'uses' =>'Backend\ServiceRequestController@requestServiceUpdate']);


        # Payment System
        Route::get('payments/orders/{order}', ['as'=> 'payments.orders.index', 'uses' => 'Backend\PaymentController@order']);
        Route::post('payments/orders/{order}', ['as'=> 'payments.orders.store', 'uses' => 'Backend\PaymentController@postOrderPayment']);
        Route::get('payments/orders/{order}/accept/{payment}', ['as'=> 'payments.orders.accept', 'uses' => 'Backend\PaymentController@orderPaymentAccept']);
        Route::get('payments/orders/{order}/accept/{payment}/confirm-accept', ['as' => 'payments.orders.confirm-accept', 'uses' => 'Backend\PaymentController@getModalAccept']);

        #Notifications
        Route::get('notifications/data',['as' => 'notifications.data', 'uses' =>'Backend\NotificationsController@data']);
        Route::get('notifications/{id}/delete', array('as' => 'notifications.delete', 'uses' => 'Backend\NotificationsController@getDelete'));
        Route::get('notifications/{id}/confirm-delete', array('as' => 'notifications.confirm-delete', 'uses' => 'Backend\NotificationsController@getModalDelete'));
        Route::resource('notifications', 'Backend\NotificationsController');

        #Newsletter
        Route::get('newsletters',['as' => 'newsletters', 'uses' =>'Backend\NewslettersController@export']);

        #############
        #Settings
        #############
        Route::group(array('prefix' => 'settings'), function () {
            #Warehouses
            Route::get('warehouses', ['as'=> 'warehouses.index', 'uses' => 'Backend\Settings\WarehouseController@index']);
            Route::post('warehouses', ['as'=> 'warehouses.store', 'uses' => 'Backend\Settings\WarehouseController@store']);
            Route::get('warehouses/create', ['as'=> 'warehouses.create', 'uses' => 'Backend\Settings\WarehouseController@create']);
            Route::put('warehouses/{warehouses}', ['as'=> 'warehouses.update', 'uses' => 'Backend\Settings\WarehouseController@update']);
            Route::patch('warehouses/{warehouses}', ['as'=> 'warehouses.update', 'uses' => 'Backend\Settings\WarehouseController@update']);
            Route::get('warehouses/{id}/delete', array('as' => 'warehouses.delete', 'uses' => 'Backend\Settings\WarehouseController@getDelete'));
            Route::get('warehouses/{id}/confirm-delete', array('as' => 'warehouses.confirm-delete', 'uses' => 'Backend\Settings\WarehouseController@getModalDelete'));
            Route::get('warehouses/{warehouses}', ['as'=> 'warehouses.show', 'uses' => 'Backend\Settings\WarehouseController@show']);
            Route::get('warehouses/{warehouses}/edit', ['as'=> 'warehouses.edit', 'uses' => 'Backend\Settings\WarehouseController@edit']);

            #Suggestions
            Route::get('suggestions', ['as'=> 'suggestions.index', 'uses' => 'Backend\Settings\SuggestionController@index']);
            Route::post('suggestions', ['as'=> 'suggestions.store', 'uses' => 'Backend\Settings\SuggestionController@store']);
            Route::get('suggestions/create', ['as'=> 'suggestions.create', 'uses' => 'Backend\Settings\SuggestionController@create']);
            Route::put('suggestions/{suggestions}', ['as'=> 'suggestions.update', 'uses' => 'Backend\Settings\SuggestionController@update']);
            Route::patch('suggestions/{suggestions}', ['as'=> 'suggestions.update', 'uses' => 'Backend\Settings\SuggestionController@update']);
            Route::get('suggestions/{id}/delete', array('as' => 'suggestions.delete', 'uses' => 'Backend\Settings\SuggestionController@getDelete'));
            Route::get('suggestions/{id}/confirm-delete', array('as' => 'suggestions.confirm-delete', 'uses' => 'Backend\Settings\SuggestionController@getModalDelete'));
            Route::get('suggestions/{suggestions}', ['as'=> 'suggestions.show', 'uses' => 'Backend\Settings\SuggestionController@show']);
            Route::get('suggestions/{suggestions}/edit', ['as'=> 'suggestions.edit', 'uses' => 'Backend\Settings\SuggestionController@edit']);

            #Services
            Route::get('services', ['as'=> 'services.index', 'uses' => 'Backend\Settings\ServiceController@index']);
            Route::post('services', ['as'=> 'services.store', 'uses' => 'Backend\Settings\ServiceController@store']);
            Route::get('services/create', ['as'=> 'services.create', 'uses' => 'Backend\Settings\ServiceController@create']);
            Route::put('services/{services}', ['as'=> 'services.update', 'uses' => 'Backend\Settings\ServiceController@update']);
            Route::patch('services/{services}', ['as'=> 'services.update', 'uses' => 'Backend\Settings\ServiceController@update']);
            Route::get('services/{id}/delete', array('as' => 'services.delete', 'uses' => 'Backend\Settings\ServiceController@getDelete'));
            Route::get('services/{id}/confirm-delete', array('as' => 'services.confirm-delete', 'uses' => 'Backend\Settings\ServiceController@getModalDelete'));
            Route::get('services/{services}', ['as'=> 'services.show', 'uses' => 'Backend\Settings\ServiceController@show']);
            Route::get('services/{services}/edit', ['as'=> 'services.edit', 'uses' => 'Backend\Settings\ServiceController@edit']);

            #DHL
            Route::get('dhl/price',['as' => 'dhl.price', 'uses' =>'Backend\Logistics\DHLController@edit']);
            Route::post('dhl/price',['as' => 'dhl.price', 'uses' =>'Backend\Logistics\DHLController@update']);
        });

        # Remaining pages will be called from below controller method
        # in real world scenario, you may be required to define all routes manually

routes/frontend.php
<?php

/*
|
| Frontend Routes
|
*/

# Authentication
Route::group(['prefix' => 'authentication'], function () {
    Route::group(['middleware' => 'guest'], function () {
        Route::get('/', ['as' => 'auth','uses' => 'Frontend\AuthController@getAuth']);
        Route::post('login', ['as' => 'login', 'uses' => 'Frontend\AuthController@postLogin']);
        Route::post('register', ['as' => 'register', 'uses' => 'Frontend\AuthController@postRegister']);
        Route::get('activate/{userId}/{activationCode}', ['as' =>'activate','uses'=>'Frontend\AuthController@getActivate']);
        Route::get('forgot-password', ['as' => 'forgot-password','uses' => 'Frontend\AuthController@getForgotPassword']);
        Route::post('forgot-password', ['as' => 'forgot-password','uses' => 'Frontend\AuthController@postForgotPassword']);
        Route::get('forgot-password-confirm/{userId}/{passwordResetCode}', ['as' => 'forgot-password-confirm', 'uses' => 'Frontend\AuthController@getForgotPasswordConfirm']);
        Route::post('forgot-password-confirm/{userId}/{passwordResetCode}', ['as' => 'forgot-password-confirm', 'uses' => 'Frontend\AuthController@postForgotPasswordConfirm']);
    });
    Route::get('logout', ['as' => 'user.logout', 'uses' => 'Frontend\AuthController@getLogout']);
});

#Static
Route::get(Lang::get('routes.static.explanation'), ['as' => 'static.explanation', 'uses' => 'Frontend\HomeController@explanation']);
Route::get(Lang::get('routes.static.shipping'), ['as' => 'static.shipping', 'uses' => 'Frontend\HomeController@shipping']);
Route::get(Lang::get('routes.static.why'), ['as' => 'static.why', 'uses' => 'Frontend\HomeController@why']);
Route::get(Lang::get('routes.static.rates'), ['as' => 'static.rates', 'uses' => 'Frontend\HomeController@rates']);
Route::get(Lang::get('routes.static.options'), ['as' => 'static.options', 'uses' => 'Frontend\HomeController@options']);
Route::get(Lang::get('routes.static.contacts'), ['as' => 'static.contacts', 'uses' => 'Frontend\HomeController@contacts']);
Route::get(Lang::get('routes.static.support'), ['as' => 'static.support', 'uses' => 'Frontend\HomeController@support']);
Route::get(Lang::get('routes.static.track'), ['as' => 'static.track', 'uses' => 'Frontend\HomeController@track']);

Route::group(['middleware' => 'SentinelUser'], function () {
    # Storage
    Route::group(['prefix' => 'storage'], function () {
        Route::get('/', ['as' => 'storage', function () {
            return Redirect::route('storage.dashboard');
        }]);

        #Dashboard
        Route::get('dashboard', ['as' => 'storage.dashboard', 'uses' => 'Frontend\StorageController@dashboard']);

        #Packages
        Route::get('packages', ['as' => 'storage.packages', 'uses' => 'Frontend\PackagesController@getPackages']);
        Route::post('packages', ['as' => 'storage.packages', 'uses' => 'Frontend\PackagesController@postPackages']);
        Route::get('packages/{package}/services/photo', ['as' => 'storage.packages.services.photo', 'uses' => 'Frontend\PackagesController@servicePhotos']);
        Route::post('packages/value', ['as' => 'storage.packages.value', 'uses' => 'Frontend\PackagesController@postPackagesValue']);
        Route::get('packages/success', ['as' => 'storage.packages.success', 'uses' => 'Frontend\PackagesController@success']);

        #Orders
        Route::get('orders', ['as' => 'storage.orders', 'uses' => 'Frontend\OrdersController@getOrders']);

        #Personal Shopper
        Route::get('personal-shopper', ['as' => 'storage.personal-shopper', 'uses' => 'Frontend\PersonalShopperController@getPersonalShopper']);
        Route::post('personal-shopper', ['as' => 'storage.personal-shopper', 'uses' => 'Frontend\PersonalShopperController@postPersonalShopper']);
        Route::get('personal-shopper/{order}', ['as' => 'storage.personal-shopper.order', 'uses' => 'Frontend\PersonalShopperController@getPersonalShopperOrder']);
        Route::post('personal-shopper-confirm/{order}', ['as' => 'storage.personal-shopper-confirm', 'uses' => 'Frontend\PersonalShopperController@confirmOrderPersonalShopper']);
        Route::get('personal-shopper-success', ['as' => 'storage.personal-shopper-success', 'uses' => 'Frontend\PersonalShopperController@success']);

        #Notifications
        Route::get('notifications', ['as' => 'storage.notifications.index', 'uses' => 'Frontend\NotificationsController@index']);
        Route::post('notifications/update', ['as' => 'storage.notifications.update', 'uses' => 'Frontend\NotificationsController@updateNotification']);

        #Options
        Route::get('options', ['as' => 'storage.options', 'uses' => 'Frontend\OptionsController@getOptions']);
        Route::post('options', ['as' => 'storage.options', 'uses' => 'Frontend\OptionsController@postOptions']);

        #Profile
        Route::group(['prefix' => 'profile'], function () {
            Route::get('edit', ['as' => 'user.profile.edit', 'uses' => 'Frontend\UserController@getProfileEdit']);
            Route::post('edit', ['as' => 'user.profile.edit', 'uses' => 'Frontend\UserController@postProfileEdit']);
        });
    });

    #Payments
    Route::get('orders/{order}/checkout', ['as' => 'storage.orders.checkout', 'uses' => 'Frontend\PaymentController@getCheckout']);
    Route::get('orders/{order}/checkout/done', ['as' => 'storage.orders.checkout.done', 'uses' => 'Frontend\PaymentController@getDone']);
    Route::get('orders/{order}/checkout/cancel', ['as' => 'storage.orders.checkout.cancel', 'uses' => 'Frontend\PaymentController@getCancel']);

});

# Spedition price for tool
Route::post('spedition/price', ['as'=> 'spedition.price', 'uses' => 'Backend\PaymentController@speditionPrice']);

# Suggestion
Route::get('suggestions/proxyme', ['as' => 'suggestions.proxyme', 'uses' => 'Frontend\SuggestionsController@proxyMe']);
Route::get('suggestions/{id?}', ['as' => 'suggestions', 'uses' => 'Frontend\SuggestionsController@index']);

# Newsletter
Route::post('newsletters', ['as'=> 'newsletters', 'uses' => 'Frontend\HomeController@newsletters']);

# Home
Route::get('/', ['as' => 'home', 'uses' => 'Frontend\HomeController@index']);

//TEMP
Route::get(Lang::get('routes.static.temp'), ['as' => 'temp', function () {
    return View::make('static.temp');
}]);

app/Http/Controllers/Frontend/NotificationsController.php
<?php namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Frontend\StorageController;
use Cartalyst\Sentinel\Checkpoints\NotActivatedException;
use Cartalyst\Sentinel\Checkpoints\ThrottlingException;
use Illuminate\Http\Request;
use Lang;
use Mail;
use Sentinel;
use URL;
use Validator;
use View;
use App\User;
use Carbon\Carbon;
use App\Helpers\Helper;
use Redirect;
use App\Item;
use App\Order;
use App\Notification;

class NotificationsController extends StorageController
{
    public function index()
    {
        $notifications = Notification::where('user_id', $this->user->id)->orderBy('id', 'DESC')->get();

        return view('storage.notifications.index', ['notifications' => $notifications]);
    }


    public function updateNotification(Request $request)
    {
        $notification = Notification::where('user_id', $this->user->id)->where('id', $request->id)->first();

        if ($notification) {
            $notification->update(['status' => 1]);

            return response()->json([], 200);
        }

        return response()->json([], 400);
    }
}

resources/views/admin/notifications/create.blade.php
@extends('admin./layouts/default')

@section('title')
Notifications
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
    <link type="text/css" href="{{ asset('assets/vendors/bootstrap-multiselect/css/bootstrap-multiselect.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/select2/css/select2.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/select2/css/select2-bootstrap.css') }}" rel="stylesheet" />
@stop

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Notifications</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Notifications</li>
        <li class="active">Create Notification</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="plus-alt" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Create new notification
                    </h4>
                </div>
                <div class="panel-body">
                     @if ($errors->any())
                        <ul class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif

                    {!! Form::open(['url' => 'admin/notifications','files'=>true]) !!}

                    <div class="form-group col-sm-12">
                        {!! Form::label('content', 'Content: ') !!}
                        {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
                    </div>

                    <!-- User Id Field -->
                    <div class="form-group col-sm-12">
                        {!! Form::label('user_id', 'Users:') !!}
                        <select class="form-control select2" id="select-user" name="user_id">
                            @foreach($users as $user)
                                <option value="{{$user->id}}" {{ (isset($package) && $package->user_id == $user->id) ? 'selected' : '' }}>{{$user->uuic}} - {{$user->first_name}} {{$user->last_name}} - {{$user->email}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <a class="btn btn-danger" href="{{ route('admin.notifications.index') }}">
                                @lang('button.cancel')
                            </a>
                            <button type="submit" class="btn btn-success">
                                @lang('button.save')
                            </button>
                        </div>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>

@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script language="javascript" type="text/javascript" src="{{ asset('assets/vendors/bootstrap-multiselect/js/bootstrap-multiselect.js') }}" ></script>
    <script language="javascript" type="text/javascript" src="{{ asset('assets/vendors/select2/js/select2.js') }}"></script>
    <script type="text/javascript">
        $("#select-user").select2({
            theme:"bootstrap",
            placeholder:"Select user..."
        });
    </script>
@stop

resources/views/admin/notifications/index.blade.php
@extends('admin./layouts/default')

@section('title')
Notifications
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
<link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
@stop

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Notifications</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Notifications</li>
        <li class="active">Notifications List</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
     @include('flash::message')
        <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Notifications List
                </h4>
            </div>
            <br />

            <div class="panel-body table-responsive">
                <table class="table table-bordered " id="notifications">
                    <thead>
                        <tr class="filters">
                            <th>ID</th>
                            <th>Content</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>UUIC</th>
                            <th>User</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
 </div>
</section>
@stop

@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}" ></script>

    <script>
        $(document).ready(function() {
            $('#notifications').dataTable( {
                "processing": true,
                "serverSide": true,
                "ajax": "{{ URL::route('admin.notifications.data') }}",
                "columns": [
                    {data: 'id', name: 'notifications.id'},
                    {data: 'content', name: 'notifications.content'},
                    {data: 'user.first_name', name: 'user.first_name', "visible": false},
                    {data: 'user.last_name', name: 'user.last_name', "visible": false},
                    {data: 'user.uuic', name: 'user.uuic', "visible": false},
                    {data: 'user.email', name: 'user.email', "visible": false},
                    {data: 'user_data', name: 'user_data'},
                    {data: 'status', name: 'notifications.status'},
                    {data: 'created_at', name: 'notifications.created_at'},
                    {data: 'actions', name: 'actions'},
                ]
            });
        });
    </script>

    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>
@stop