routes/backend.php
<?php
/**
 * Model binding into route
 */
Route::model('users', 'App\User');
Route::pattern('slug', '[a-z0-9- _]+');

/*
|
| Admin Routes
|
*/
Route::group(array('prefix' => 'admin'), function () {

    # Error pages should be shown without requiring login
    Route::get('404', function () {
        return View('admin/404');
    });
    Route::get('500', function () {
        return View::make('admin/500');
    });

    # All basic routes defined here
    Route::get('signin', array('as' => 'signin', 'uses' => 'Backend\AuthController@getSignin'));
    Route::post('signin', 'Backend\AuthController@postSignin');
    Route::get('logout', array('as' => 'logout', 'uses' => 'Backend\AuthController@getLogout'));

    Route::group(['middleware' => 'SentinelAdmin', 'as' => 'admin.'], function () {
        # Dashboard / Index
        Route::get('/', array('as' => 'dashboard','uses' => 'JoshController@showHome'));

        # User Management
        Route::group(array('prefix' => 'users'), function () {
            Route::get('/', array('as' => 'users', 'uses' => 'Backend\UsersController@index'));
            Route::get('data',['as' => 'users.data', 'uses' =>'Backend\UsersController@data']);
            Route::get('create', 'Backend\UsersController@create');
            Route::post('create', 'Backend\UsersController@store');
            Route::get('{user}', array('as' => 'users.show', 'uses' => 'Backend\UsersController@show'));
            Route::get('{user}/destroy', array('as' => 'users.total-destroy', 'uses' => 'Backend\UsersController@destroy'));
            Route::get('{user}/delete', array('as' => 'users.delete', 'uses' => 'Backend\UsersController@delete'));
            Route::get('{user}/confirm-delete', array('as' => 'users.confirm-delete', 'uses' => 'Backend\UsersController@getModalDelete'));
            Route::get('{user}/confirm-destroy', array('as' => 'users.confirm-destroy', 'uses' => 'Backend\UsersController@getModalDestroy'));
            Route::get('{user}/restore', array('as' => 'restore/user', 'uses' => 'Backend\UsersController@getRestore'));
            Route::post('{user}/passwordreset', array('as' => 'passwordreset', 'uses' => 'Backend\UsersController@passwordreset'));
        });
        Route::resource('users', 'Backend\UsersController');
        Route::get('deleted_users',array('as' => 'deleted_users','before' => 'Sentinel', 'uses' => 'Backend\UsersController@getDeletedUsers'));

        # Group Management
        Route::group(array('prefix' => 'groups'), function () {
            Route::get('/', array('as' => 'groups', 'uses' => 'Backend\GroupsController@index'));
            Route::get('create', array('as' => 'groups.create', 'uses' => 'Backend\GroupsController@create'));
            Route::post('create', 'Backend\GroupsController@store');
            Route::get('{group}/edit', array('as' => 'groups.edit', 'uses' => 'Backend\GroupsController@edit'));
            Route::post('{group}/edit', 'Backend\GroupsController@update');
            Route::get('{group}/delete', array('as' => 'groups.delete', 'uses' => 'Backend\GroupsController@destroy'));
            Route::get('{group}/confirm-delete', array('as' => 'groups.confirm-delete', 'uses' => 'Backend\GroupsController@getModalDelete'));
            Route::get('{group}/restore', array('as' => 'groups.restore', 'uses' => 'Backend\GroupsController@getRestore'));
        });

        # Packages Management
        Route::get('packages', ['as'=> 'packages.index', 'uses' => 'Backend\PackageController@index']);
        Route::get('packages/data',['as' => 'packages.data', 'uses' =>'Backend\PackageController@data']);
        Route::get('packages/photo/data',['as' => 'packages.photo.data', 'uses' =>'Backend\PackageController@photoData']);
        Route::post('packages', ['as'=> 'packages.store', 'uses' => 'Backend\PackageController@store']);
        Route::get('packages/create', ['as'=> 'packages.create', 'uses' => 'Backend\PackageController@create']);
        Route::get('packages/service/photo',['as' => 'packages.service.photo', 'uses' =>'Backend\PackageController@indexServicePhoto']);
        Route::put('packages/{packages}', ['as'=> 'packages.update', 'uses' => 'Backend\PackageController@update']);
        Route::patch('packages/{packages}', ['as'=> 'packages.update', 'uses' => 'Backend\PackageController@update']);
        Route::get('packages/{id}/delete', array('as' => 'packages.delete', 'uses' => 'Backend\PackageController@getDelete'));
        Route::get('packages/{id}/destroy', array('as' => 'packages.total-destroy', 'uses' => 'Backend\PackageController@destroy'));
        Route::get('packages/{id}/confirm-delete', array('as' => 'packages.confirm-delete', 'uses' => 'Backend\PackageController@getModalDelete'));
        Route::get('packages/{id}/confirm-destroy', array('as' => 'packages.confirm-destroy', 'uses' => 'Backend\PackageController@getModalDestroy'));
        Route::get('packages/{id}/restore', array('as' => 'restore/package', 'uses' => 'Backend\PackageController@getRestore'));
        Route::get('packages/{packages}', ['as'=> 'packages.show', 'uses' => 'Backend\PackageController@show']);
        Route::get('packages/{packages}/edit', ['as'=> 'packages.edit', 'uses' => 'Backend\PackageController@edit']);
        Route::get('deleted_packages',array('as' => 'deleted_packages','before' => 'Sentinel', 'uses' => 'Backend\PackageController@getDeletedPackages'));

        # Orders Management
        Route::get('orders', ['as'=> 'orders.index', 'uses' => 'Backend\OrderController@index']);
        Route::get('orders/lists/new',['as' => 'orders.lists.new', 'uses' =>'Backend\OrderController@index']);
        Route::get('orders/lists/new/data',['as' => 'orders.lists.new.data', 'uses' =>'Backend\OrderController@dataOrdersNew']);
        Route::get('orders/lists/paid',['as' => 'orders.lists.paid', 'uses' =>'Backend\OrderController@index']);
        Route::get('orders/lists/paid/data',['as' => 'orders.lists.paid.data', 'uses' =>'Backend\OrderController@dataOrdersPaid']);
        Route::get('orders/data',['as' => 'orders.data', 'uses' =>'Backend\OrderController@data']);
        Route::get('orders/requests/data',['as' => 'orders.requests.data', 'uses' =>'Backend\OrderController@requestsData']);
        Route::post('orders', ['as'=> 'orders.store', 'uses' => 'Backend\OrderController@store']);
        Route::get('orders/requests', ['as'=> 'orders.request', 'uses' => 'Backend\OrderController@indexOrderRequests']);
        Route::get('orders/create', ['as'=> 'orders.create', 'uses' => 'Backend\OrderController@create']);
        Route::put('orders/{orders}', ['as'=> 'orders.update', 'uses' => 'Backend\OrderController@update']);
        Route::patch('orders/{orders}', ['as'=> 'orders.update', 'uses' => 'Backend\OrderController@update']);
        Route::get('orders/{id}/delete', array('as' => 'orders.delete', 'uses' => 'Backend\OrderController@getDelete'));
        Route::get('orders/{id}/destroy', array('as' => 'orders.total-destroy', 'uses' => 'Backend\OrderController@destroy'));
        Route::get('orders/{id}/confirm-delete', array('as' => 'orders.confirm-delete', 'uses' => 'Backend\OrderController@getModalDelete'));
        Route::get('orders/{id}/confirm-destroy', array('as' => 'orders.confirm-destroy', 'uses' => 'Backend\OrderController@getModalDestroy'));
        Route::get('orders/{id}/restore', array('as' => 'restore/order', 'uses' => 'Backend\OrderController@getRestore'));
        Route::get('orders/{orders}', ['as'=> 'orders.show', 'uses' => 'Backend\OrderController@show']);
        Route::get('orders/{orders}/edit', ['as'=> 'orders.edit', 'uses' => 'Backend\OrderController@edit']);
        Route::get('deleted_orders',array('as' => 'deleted_orders','before' => 'Sentinel', 'uses' => 'Backend\OrderController@getDeletedOrders'));

        # Personal Shopper Management
        Route::get('personalShoppers', ['as'=> 'personalShoppers.index', 'uses' => 'Backend\PersonalShopperController@index']);
        Route::get('personalShoppers/data',['as' => 'personalShoppers.data', 'uses' =>'Backend\PersonalShopperController@data']);
        Route::post('personalShoppers', ['as'=> 'personalShoppers.store', 'uses' => 'Backend\PersonalShopperController@store']);
        Route::get('personalShoppers/create', ['as'=> 'personalShoppers.create', 'uses' => 'Backend\PersonalShopperController@create']);
        Route::put('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.update', 'uses' => 'Backend\PersonalShopperController@update']);
        Route::patch('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.update', 'uses' => 'Backend\PersonalShopperController@update']);
        Route::get('personalShoppers/{id}/delete', array('as' => 'personalShoppers.delete', 'uses' => 'Backend\PersonalShopperController@getDelete'));
        Route::get('personalShoppers/{id}/destroy', array('as' => 'personalShoppers.total-destroy', 'uses' => 'Backend\PersonalShopperController@destroy'));
        Route::get('personalShoppers/{id}/confirm-delete', array('as' => 'personalShoppers.confirm-delete', 'uses' => 'Backend\PersonalShopperController@getModalDelete'));
        Route::get('personalShoppers/{id}/confirm-destroy', array('as' => 'personalShoppers.confirm-destroy', 'uses' => 'Backend\PersonalShopperController@getModalDestroy'));
        Route::get('personalShoppers/{id}/restore', array('as' => 'restore/personalShopper', 'uses' => 'Backend\PersonalShopperController@getRestore'));
        Route::get('personalShoppers/{personalShoppers}', ['as'=> 'personalShoppers.show', 'uses' => 'Backend\PersonalShopperController@show']);
        Route::get('personalShoppers/{personalShoppers}/edit', ['as'=> 'personalShoppers.edit', 'uses' => 'Backend\PersonalShopperController@edit']);
        Route::get('deleted_personalShoppers',array('as' => 'deleted_personalShoppers','before' => 'Sentinel', 'uses' => 'Backend\PersonalShopperController@getDeletedOrders'));

        # Service Request

routes/frontend.php
<?php

/*
|
| Frontend Routes
|
*/

# Authentication
Route::group(['prefix' => 'authentication'], function () {
    Route::group(['middleware' => 'guest'], function () {
        Route::get('/', ['as' => 'auth','uses' => 'Frontend\AuthController@getAuth']);
        Route::post('login', ['as' => 'login', 'uses' => 'Frontend\AuthController@postLogin']);
        Route::post('register', ['as' => 'register', 'uses' => 'Frontend\AuthController@postRegister']);
        Route::get('activate/{userId}/{activationCode}', ['as' =>'activate','uses'=>'Frontend\AuthController@getActivate']);
        Route::get('forgot-password', ['as' => 'forgot-password','uses' => 'Frontend\AuthController@getForgotPassword']);
        Route::post('forgot-password', ['as' => 'forgot-password','uses' => 'Frontend\AuthController@postForgotPassword']);
        Route::get('forgot-password-confirm/{userId}/{passwordResetCode}', ['as' => 'forgot-password-confirm', 'uses' => 'Frontend\AuthController@getForgotPasswordConfirm']);
        Route::post('forgot-password-confirm/{userId}/{passwordResetCode}', ['as' => 'forgot-password-confirm', 'uses' => 'Frontend\AuthController@postForgotPasswordConfirm']);
    });
    Route::get('logout', ['as' => 'user.logout', 'uses' => 'Frontend\AuthController@getLogout']);
});

#Static
Route::get(Lang::get('routes.static.explanation'), ['as' => 'static.explanation', 'uses' => 'Frontend\HomeController@explanation']);
Route::get(Lang::get('routes.static.shipping'), ['as' => 'static.shipping', 'uses' => 'Frontend\HomeController@shipping']);
Route::get(Lang::get('routes.static.why'), ['as' => 'static.why', 'uses' => 'Frontend\HomeController@why']);
Route::get(Lang::get('routes.static.rates'), ['as' => 'static.rates', 'uses' => 'Frontend\HomeController@rates']);
Route::get(Lang::get('routes.static.options'), ['as' => 'static.options', 'uses' => 'Frontend\HomeController@options']);
Route::get(Lang::get('routes.static.contacts'), ['as' => 'static.contacts', 'uses' => 'Frontend\HomeController@contacts']);
Route::get(Lang::get('routes.static.support'), ['as' => 'static.support', 'uses' => 'Frontend\HomeController@support']);
Route::get(Lang::get('routes.static.track'), ['as' => 'static.track', 'uses' => 'Frontend\HomeController@track']);

Route::group(['middleware' => 'SentinelUser'], function () {
    # Storage
    Route::group(['prefix' => 'storage'], function () {
        Route::get('/', ['as' => 'storage', function () {
            return Redirect::route('storage.dashboard');
        }]);

        #Dashboard
        Route::get('dashboard', ['as' => 'storage.dashboard', 'uses' => 'Frontend\StorageController@dashboard']);

        #Packages
        Route::get('packages', ['as' => 'storage.packages', 'uses' => 'Frontend\PackagesController@getPackages']);
        Route::post('packages', ['as' => 'storage.packages', 'uses' => 'Frontend\PackagesController@postPackages']);
        Route::get('packages/{package}/services/photo', ['as' => 'storage.packages.services.photo', 'uses' => 'Frontend\PackagesController@servicePhotos']);
        Route::post('packages/value', ['as' => 'storage.packages.value', 'uses' => 'Frontend\PackagesController@postPackagesValue']);
        Route::get('packages/success', ['as' => 'storage.packages.success', 'uses' => 'Frontend\PackagesController@success']);

        #Orders
        Route::get('orders', ['as' => 'storage.orders', 'uses' => 'Frontend\OrdersController@getOrders']);

        #Personal Shopper
        Route::get('personal-shopper', ['as' => 'storage.personal-shopper', 'uses' => 'Frontend\PersonalShopperController@getPersonalShopper']);
        Route::post('personal-shopper', ['as' => 'storage.personal-shopper', 'uses' => 'Frontend\PersonalShopperController@postPersonalShopper']);
        Route::get('personal-shopper/{order}', ['as' => 'storage.personal-shopper.order', 'uses' => 'Frontend\PersonalShopperController@getPersonalShopperOrder']);
        Route::post('personal-shopper-confirm/{order}', ['as' => 'storage.personal-shopper-confirm', 'uses' => 'Frontend\PersonalShopperController@confirmOrderPersonalShopper']);
        Route::get('personal-shopper-success', ['as' => 'storage.personal-shopper-success', 'uses' => 'Frontend\PersonalShopperController@success']);

        #Notifications
        Route::get('notifications', ['as' => 'storage.notifications.index', 'uses' => 'Frontend\NotificationsController@index']);
        Route::post('notifications/update', ['as' => 'storage.notifications.update', 'uses' => 'Frontend\NotificationsController@updateNotification']);

        #Options
        Route::get('options', ['as' => 'storage.options', 'uses' => 'Frontend\OptionsController@getOptions']);
        Route::post('options', ['as' => 'storage.options', 'uses' => 'Frontend\OptionsController@postOptions']);

        #Profile
        Route::group(['prefix' => 'profile'], function () {
            Route::get('edit', ['as' => 'user.profile.edit', 'uses' => 'Frontend\UserController@getProfileEdit']);
            Route::post('edit', ['as' => 'user.profile.edit', 'uses' => 'Frontend\UserController@postProfileEdit']);
        });
    });

    #Payments
    Route::get('orders/{order}/checkout', ['as' => 'storage.orders.checkout', 'uses' => 'Frontend\PaymentController@getCheckout']);
    Route::get('orders/{order}/checkout/done', ['as' => 'storage.orders.checkout.done', 'uses' => 'Frontend\PaymentController@getDone']);
    Route::get('orders/{order}/checkout/cancel', ['as' => 'storage.orders.checkout.cancel', 'uses' => 'Frontend\PaymentController@getCancel']);

});

# Spedition price for tool
Route::post('spedition/price', ['as'=> 'spedition.price', 'uses' => 'Backend\PaymentController@speditionPrice']);

# Suggestion
Route::get('suggestions/proxyme', ['as' => 'suggestions.proxyme', 'uses' => 'Frontend\SuggestionsController@proxyMe']);
Route::get('suggestions/{id?}', ['as' => 'suggestions', 'uses' => 'Frontend\SuggestionsController@index']);

# Newsletter
Route::post('newsletters', ['as'=> 'newsletters', 'uses' => 'Frontend\HomeController@newsletters']);

# Home
Route::get('/', ['as' => 'home', 'uses' => 'Frontend\HomeController@index']);

//TEMP
Route::get(Lang::get('routes.static.temp'), ['as' => 'temp', function () {
    return View::make('static.temp');
}]);

resources/views/admin/groups/create.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
    @lang('admin/groups/title.create')
    @parent
@stop

{{-- Content --}}
@section('content')
<section class="content-header">
    <h1>
        @lang('groups/title.create')
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                @lang('general.dashboard')
            </a>
        </li>
        <li>@lang('groups/title.groups')</li>
        <li class="active">
            @lang('groups/title.create')
        </li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        @lang('groups/title.create')
                    </h4>
                </div>
                <div class="panel-body">
                    {!! $errors->first('slug', '<span class="help-block">Another role with same slug exists, please choose another name</span> ') !!}
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form class="form-horizontal" role="form" method="post" action="">
                        <!-- CSRF Token -->
                        <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                        <div class="form-group {{ $errors->
                            first('name', 'has-error') }}">
                            <label for="title" class="col-sm-2 control-label">
                                @lang('groups/form.name')
                            </label>
                            <div class="col-sm-5">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Group Name"
                                       value="{!! old('name') !!}">
                            </div>
                            <div class="col-sm-4">
                                {!! $errors->first('name', '<span class="help-block">:message</span> ') !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-4">
                                <a class="btn btn-danger" href="{{ route('admin.groups') }}">
                                    @lang('button.cancel')
                                </a>
                                <button type="submit" class="btn btn-success">
                                    @lang('button.save')
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>
@stop

resources/views/admin/groups/edit.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
@lang('groups/title.edit')
@parent
@stop

{{-- Content --}}
@section('content')
<section class="content-header">
    <h1>
        @lang('groups/title.edit')
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                @lang('general.dashboard')
            </a>
        </li>
        <li>@lang('groups/title.groups')</li>
        <li class="active">@lang('groups/title.edit')</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="wrench" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        @lang('groups/title.edit')
                    </h4>
                </div>
                <div class="panel-body">
                    @if($role)
                        <form class="form-horizontal" role="form" method="post" action="">
                            <!-- CSRF Token -->
                            <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                            <div class="form-group {{ $errors->
                                first('name', 'has-error') }}">
                                <label for="title" class="col-sm-2 control-label">
                                    @lang('groups/form.name')
                                </label>
                                <div class="col-sm-5">
                                    <input type="text" id="name" name="name" class="form-control"
                                           placeholder=@lang('groups/form.name') value="{!! old('name', $role->
                                    name) !!}">
                                </div>
                                <div class="col-sm-4">
                                    {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="slug" class="col-sm-2 control-label">@lang('groups/form.slug')</label>
                                <div class="col-sm-5">
                                    <input type="text" class="form-control" value="{!! $role->slug !!}" readonly />
                                </div>
                            </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-4">
                                <a class="btn btn-danger" href="{{ route('admin.groups') }}">
                                    @lang('button.cancel')
                                </a>
                                <button type="submit" class="btn btn-success">
                                    @lang('button.save')
                                </button>
                            </div>
                        </div>
                    </form>
                    @else
                        <h1>@lang('groups/message.no_role_exists')</h1>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>

@stop

resources/views/admin/groups/index.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
@lang('groups/title.management')
@parent
@stop

{{-- Content --}}
@section('content')
<section class="content-header">
    <h1>@lang('groups/title.management')</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                @lang('general.dashboard')
            </a>
        </li>
        <li><a href="#"> @lang('groups/title.groups')</a></li>
        <li class="active">@lang('groups/title.groups_list')</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left"> <i class="livicon" data-name="users" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        @lang('groups')
                    </h4>
                    <div class="pull-right">
                    <a href="{{ route('admin.groups.create') }}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> @lang('button.create')</a>
                    </div>
                </div>
                <br />
                <div class="panel-body">
                    @if ($roles->count() >= 1)

                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>@lang('groups/table.id')</th>
                                    <th>@lang('groups/table.name')</th>
                                    <th>@lang('groups/table.users')</th>
                                    <th>@lang('groups/table.created_at')</th>
                                    <th>@lang('groups/table.actions')</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($roles as $role)
                                <tr>
                                    <td>{!! $role->id !!}</td>
                                    <td>{!! $role->name !!}</td>
                                    <td>{!! $role->users()->count() !!}</td>
                                    <td>{!! $role->created_at->diffForHumans() !!}</td>
                                    <td>
                                        <a href="{{ route('admin.groups.edit', $role->id) }}">
                                                <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="edit group"></i>
                                            </a>
                                            <!-- let's not delete 'Admin' group by accident -->
                                            @if ($role->id !== 1)
                                                @if($role->users()->count())
                                                    <a href="#" data-toggle="modal" data-target="#users_exists" data-name="{!! $role->name !!}" class="users_exists">
                                                        <i class="livicon" data-name="warning-alt" data-size="18"
                                                           data-loop="true" data-c="#f56954" data-hc="#f56954"
                                                           title="@lang('groups/form.users_exists')"></i>
                                                    </a>
                                                @else
                                                    <a href="{{ route('admin.groups.confirm-delete', $role->id) }}" data-toggle="modal" data-target="#delete_confirm">
                                                        <i class="livicon" data-name="remove-alt" data-size="18"
                                                           data-loop="true" data-c="#f56954" data-hc="#f56954"
                                                           title="@lang('groups/form.delete_group')"></i>
                                                    </a>
                                                @endif

                                            @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                        @lang('general.noresults')
                    @endif   
                </div>
            </div>
        </div>
    </div>    <!-- row-->
</section>




@stop

{{-- Body Bottom confirm modal --}}
@section('footer_scripts')
<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
<div class="modal fade" id="users_exists" tabindex="-2" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                @lang('groups/message.users_exists')
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});
    $(document).on("click", ".users_exists", function () {

        var group_name = $(this).data('name');
        $(".modal-header h4").text( group_name+" Group" );
    });</script>
@stop